name: Docker

on:
  push:
    branches:
      - development

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: |
          docker build -t dpadhan/myapplication:${{ github.ref_name }} .

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: dpadhan
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: |
          docker push dpadhan/myapplication:${{ github.ref_name }}
